import { Buffer } from 'node:buffer';
import { mkdir, readdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const require = createRequire(import.meta.url);
const sourceRoot = dirname(require.resolve('@iconify/json/package.json'));
const output = resolve(
  root,
  'packages/@core/base/icons/src/local-icons/generated',
);
const config = JSON.parse(
  await readFile(
    resolve(root, 'scripts/icons/local-icons.config.json'),
    'utf8',
  ),
);
const sourceVersion = JSON.parse(
  await readFile(resolve(sourceRoot, 'package.json'), 'utf8'),
).version;
const check = process.argv.includes('--check');
const validName = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const sources = new Map();
if (
  !Array.isArray(config.collections) ||
  !Array.isArray(config.icons) ||
  ![...config.collections, ...config.icons].every(
    (item) => typeof item === 'string',
  )
) {
  throw new Error('collections and icons must be arrays of strings');
}

async function source(prefix) {
  if (!validName.test(prefix)) throw new Error(`Invalid collection: ${prefix}`);
  if (!sources.has(prefix)) {
    sources.set(
      prefix,
      JSON.parse(
        await readFile(resolve(sourceRoot, `json/${prefix}.json`), 'utf8'),
      ),
    );
  }
  return sources.get(prefix);
}

// Retain collection defaults and attribution; aliases may inherit other aliases.
function subset(data, names) {
  const {
    icons,
    aliases,
    categories: _categories,
    chars: _chars,
    themes: _themes,
    prefixes: _prefixes,
    suffixes: _suffixes,
    ...metadata
  } = data;
  const result = { ...metadata, icons: {}, aliases: {} };
  function include(name, visiting = new Set()) {
    if (visiting.has(name))
      throw new Error(`Circular alias: ${data.prefix}:${name}`);
    if (result.icons[name] || result.aliases[name]) return;
    if (icons[name]) result.icons[name] = icons[name];
    else if (aliases?.[name]) {
      include(aliases[name].parent, new Set([name, ...visiting]));
      result.aliases[name] = aliases[name];
    } else throw new Error(`Unknown icon: ${data.prefix}:${name}`);
  }
  for (const name of [...names].toSorted()) include(name);
  return result;
}

const selected = new Map();
for (const id of new Set(config.icons)) {
  const [prefix, name, extra] = id.split(':');
  if (
    !validName.test(prefix) ||
    !name ||
    !validName.test(name) ||
    extra !== undefined
  ) {
    throw new Error(`Invalid icon: ${id}`);
  }
  if (!selected.has(prefix)) selected.set(prefix, new Set());
  selected.get(prefix).add(name);
}
const files = new Map();
const base = [];
for (const [prefix, names] of [...selected].toSorted(([a], [b]) =>
  a.localeCompare(b),
)) {
  base.push(subset(await source(prefix), names));
}
files.set('base.json', JSON.stringify(base));
const collections = [];
for (const prefix of [...new Set(config.collections)].toSorted()) {
  const data = await source(prefix);
  files.set(`${prefix}.json`, JSON.stringify(data));
  collections.push({ prefix, title: data.info?.name || prefix });
}
files.set(
  'manifest.json',
  JSON.stringify({
    sourceVersion,
    collections,
    icons: [...new Set(config.icons)].toSorted(),
  }),
);
// Explicit imports let both Vite and unbuild emit a separate chunk per collection.
files.set(
  'loaders.ts',
  `// Generated by pnpm icons:generate. Do not edit.\nexport const collectionLoaders = {\n${collections.map(({ prefix }) => `  '${prefix}': () => import('./${prefix}.json').then((module) => module.default),`).join('\n')}\n};\n`,
);

await mkdir(output, { recursive: true });
let stale = false;
for (const [name, content] of files) {
  const text = `${content.trimEnd()}\n`;
  if (check) {
    const current = await readFile(resolve(output, name), 'utf8').catch(
      () => null,
    );
    if (current !== text) {
      console.error(`Outdated generated file: ${name}`);
      stale = true;
    }
  } else await writeFile(resolve(output, name), text);
  if (name.endsWith('.json'))
    console.log(
      `${name}: ${(Buffer.byteLength(text) / 1024).toFixed(1)} KiB, gzip ${(gzipSync(text).length / 1024).toFixed(1)} KiB`,
    );
}
for (const name of await readdir(output)) {
  if (files.has(name)) continue;
  if (check) {
    console.error(`Obsolete generated file: ${name}`);
    stale = true;
  } else await unlink(resolve(output, name));
}
if (stale) process.exitCode = 1;
