import { PRESET_ICONS } from '#/views/my-hub/exercise/category-config/config';

interface DictIconPreset {
  icon: string;
  label: string;
}

const EXERCISE_ICON_LABELS: Record<string, string> = {
  'mdi:run': '跑步',
  'mdi:bike': '骑行',
  'mdi:swim': '游泳',
  'mdi:dumbbell': '哑铃',
  'svg:ab-wheel': '健腹轮',
  'svg:plank': '平板支撑',
  'svg:push-up': '俯卧撑',
  'svg:sit-up': '仰卧起坐',
  'svg:pull-up': '引体向上',
  'svg:chin-up': '反手引体向上',
  'svg:bench-press': '卧推',
  'svg:barbell-curl': '杠铃弯举',
  'svg:reverse-crunch': '反向卷腹',
  'mdi:weight-lifter': '举重',
  'mdi:yoga': '瑜伽',
  'mdi:basketball': '篮球',
  'mdi:soccer': '足球',
  'mdi:tennis': '网球',
  'mdi:badminton': '羽毛球',
  'mdi:table-tennis': '乒乓球',
  'mdi:volleyball': '排球',
  'mdi:baseball': '棒球',
  'mdi:golf': '高尔夫',
  'mdi:bowling': '保龄球',
  'mdi:hiking': '徒步',
  'mdi:jump-rope': '跳绳',
  'mdi:skateboarding': '滑板',
  'mdi:roller-skate': '轮滑',
  'mdi:snowboard': '单板滑雪',
  'mdi:ski': '双板滑雪',
  'mdi:boxing-glove': '拳击',
  'mdi:karate': '空手道',
  'mdi:sword-cross': '击剑',
  'mdi:arm-flex': '手臂训练',
  'mdi:human-handsup': '拉伸',
  'mdi:shoe-sneaker': '运动鞋',
  'mdi:tshirt-crew': '运动服',
  'mdi:water': '饮水',
  'mdi:fire': '热量',
  'mdi:heart-pulse': '心率',
  'mdi:stopwatch': '秒表',
  'mdi:timer': '计时器',
  'mdi:whistle': '哨子',
  'mdi:medal': '奖牌',
  'mdi:trophy': '奖杯',
  'mdi:flag-checkered': '终点',
  'mdi:target': '目标',
  'mdi:star': '星标',
  'mdi:lightning-bolt': '能量',
};

const DEFAULT_ICONS: DictIconPreset[] = [
  { icon: 'mdi:tag', label: '标签' },
  { icon: 'mdi:folder', label: '分类' },
  { icon: 'mdi:star', label: '星标' },
  { icon: 'mdi:bookmark', label: '收藏' },
];

const DICT_ICON_PRESETS: Record<string, DictIconPreset[]> = {
  exercise_type: PRESET_ICONS.map(({ icon }) => ({
    icon,
    label: EXERCISE_ICON_LABELS[icon] ?? icon,
  })),
  device_type: [
    { icon: 'mdi:cellphone', label: '手机' },
    { icon: 'mdi:laptop', label: '笔记本电脑' },
    { icon: 'mdi:desktop-tower-monitor', label: '台式电脑' },
    { icon: 'mdi:tablet', label: '平板' },
    { icon: 'mdi:monitor', label: '显示器' },
    { icon: 'mdi:headphones', label: '耳机' },
    { icon: 'mdi:camera', label: '相机' },
    { icon: 'mdi:watch', label: '手表' },
    { icon: 'mdi:keyboard', label: '键盘' },
    { icon: 'mdi:mouse', label: '鼠标' },
    { icon: 'mdi:printer', label: '打印机' },
    { icon: 'mdi:router-wireless', label: '路由器' },
    { icon: 'mdi:speaker', label: '音箱' },
    { icon: 'mdi:gamepad-variant', label: '游戏设备' },
    { icon: 'mdi:television', label: '电视' },
    { icon: 'mdi:harddisk', label: '硬盘' },
  ],
  exp_type: [
    { icon: 'mdi:food', label: '餐饮' },
    { icon: 'mdi:cart', label: '购物' },
    { icon: 'mdi:bus', label: '公共交通' },
    { icon: 'mdi:car', label: '用车' },
    { icon: 'mdi:home', label: '住房' },
    { icon: 'mdi:medical-bag', label: '医疗' },
    { icon: 'mdi:school', label: '教育' },
    { icon: 'mdi:movie', label: '娱乐' },
    { icon: 'mdi:airplane', label: '旅行' },
    { icon: 'mdi:tshirt-crew', label: '服饰' },
    { icon: 'mdi:phone', label: '通信' },
    { icon: 'mdi:gift', label: '礼物' },
    { icon: 'mdi:paw', label: '宠物' },
    { icon: 'mdi:lightning-bolt', label: '电费' },
    { icon: 'mdi:water', label: '水费' },
    { icon: 'mdi:tools', label: '维修' },
  ],
  income_type: [
    { icon: 'mdi:briefcase', label: '工资' },
    { icon: 'mdi:medal', label: '奖金' },
    { icon: 'mdi:laptop', label: '兼职' },
    { icon: 'mdi:chart-line', label: '投资收益' },
    { icon: 'mdi:bank', label: '利息' },
    { icon: 'mdi:gift', label: '红包' },
    { icon: 'mdi:cash-refund', label: '退款' },
    { icon: 'mdi:home', label: '租金收入' },
    { icon: 'mdi:store', label: '经营收入' },
    { icon: 'mdi:hand-coin', label: '补贴' },
    { icon: 'mdi:copyright', label: '稿费版权' },
    { icon: 'mdi:cash-plus', label: '其他收入' },
  ],
  pay_type: [
    { icon: 'mdi:cash', label: '现金' },
    { icon: 'mdi:bank', label: '银行账户' },
    { icon: 'mdi:credit-card-outline', label: '银行卡' },
    { icon: 'mdi:credit-card', label: '信用卡' },
    { icon: 'mdi:wallet', label: '钱包' },
    { icon: 'mdi:cellphone-nfc', label: '手机支付' },
    { icon: 'mdi:qrcode-scan', label: '扫码支付' },
    { icon: 'mdi:bank-transfer', label: '银行转账' },
    { icon: 'ant-design:alipay-outlined', label: '支付宝' },
    { icon: 'ant-design:wechat-outlined', label: '微信支付' },
  ],
};

export function getDictIconPresets(dictType: string): DictIconPreset[] {
  return Object.hasOwn(DICT_ICON_PRESETS, dictType)
    ? DICT_ICON_PRESETS[dictType]!
    : DEFAULT_ICONS;
}
